### ISSUE TITLE
Sql errors in almost every JtextField

### ISSUE THREAD

**Issue by Saeed-Muhaisen** [Saeed-Muhaisen/PharmacyProject#11]
If we insert letters instead of numbers in search fields or id fields we get sql errors, i don't think this is possible to be solved from backend, it should be frontend. 
Can someone check it please.

**Comment by Eecekkaratas** [comment]
i added keylisteners to admin view and i think the issue is fixed there, i can do for the rest later

**Comment by tugceozgirgin** [comment]
I did the same thing for pharmacistView, but the issue is we cannot use capital letters now in any JtextField that required letters

**Comment by elifozmen** [comment]
i finished it for pharmacistView and i checked doctor and it seems everything now is restricted to either letters or numbers
