### ISSUE TITLE
Transaction history panel in adminView 

### ISSUE THREAD

**Issue by tugceozgirgin** [Saeed-Muhaisen/PharmacyProject#12]
I added the functionalities for adminView, but i keep getting a bug from adminView about patient being null, i found an issue and fixed in PatientAPI, but still its not working, it keeps giving null pointer error.

**Comment by Saeed-Muhaisen** [comment]
Fixed it, you made a small mistake in TransactionHistory methods that you used for the TransactionRowmapper function.
