### ISSUE TITLE
DoctorView issue creating/editing prescriptions

### ISSUE THREAD

**Issue by Eecekkaratas** [Saeed-Muhaisen/PharmacyProject#2]
When i create a prescription for a patient, and then go and create a new prescription for another patient, the tables are already filled for the druglist with old information from old prescription. Also editing a Prescirption has same issue, i am not sure if its frontend issue or backend database related.

**Comment by JanaAyoub** [comment]
Fixed: it was editing not correctly switching between true and false, and active_prescription was not correctly updating itself
