### ISSUE TITLE
edit/delete bug AdminView

### ISSUE THREAD

**Issue by tugceozgirgin** [Saeed-Muhaisen/PharmacyProject#7]
Sometimes edit and delete aren't functioning and i dont know why, they dont show any errors they just stop working

**Comment by Saeed-Muhaisen** [comment]
same thing is in DoctorView when adding a patient, it didn't work until i putted println in it. idk what is causing it tho

**Comment by Saeed-Muhaisen** [comment]
I think it was schema issues, i dropped the db and re added everything and i no longer saw this issue again
