### ISSUE TITLE
Doctor/Pharmacist/Admin account names

### ISSUE THREAD

**Issue by tugceozgirgin** [Saeed-Muhaisen/PharmacyProject#8]
I created a trigger that would automatically add useraccounts with the usernames same as the doctor/pharmacy/admin name but now if we add a doctor with the name X and try to add pharmacist with same name then we get an error. I couldn't think of a way to fix it

**Comment by Saeed-Muhaisen** [comment]
I dont think its possible to solve this, each username must be unique so i think we will have to leave it as it is
