### ISSUE TITLE
Database Issue for prescription in DoctorView

### ISSUE THREAD

**Issue by JanaAyoub** [Saeed-Muhaisen/PharmacyProject#9]
In doctorView, if we create a new prescription with a drug in it, and push it to the db. 
Then search for it and edit this prescription and remove the drug from it and make it empty prescription, it still saves it in the database. 
Is this normal or can someone make a trigger for deleting prescriptions with empty druglist?

**Comment by JanaAyoub** [comment]
i might have fixed it but there is a small issue, if we try to sell a drug where capacity in inventory equals the amount we want to sell then an error shows up. can someone take a look?

**Comment by Saeed-Muhaisen** [comment]
I fixed it by an if statement to check if the prescription is empty or not, if it is after editing then the prescription gets deleted. if its empty after adding then the prescription never gets added.
